name: action-runner
on:
  push:
  schedule:
    - cron: '0 1 * * 0'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: phaze9/action-runner
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
